name: nexora_mobile
description: Nexora — application mobile (Android & iOS) de la marketplace de proximité.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0          # appels REST vers l'API Jakarta EE
  google_fonts: ^6.2.1  # Poppins (identité Nexora)
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
