package sn.ucad.nexora.espace.infrastructure.security;
import org.springframework.context.annotation.Bean; import org.springframework.context.annotation.Configuration; import org.springframework.http.HttpMethod; import org.springframework.security.config.annotation.web.builders.HttpSecurity; import org.springframework.security.config.http.SessionCreationPolicy; import org.springframework.security.web.SecurityFilterChain; import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter; import sn.ucad.nexora.espace.infrastructure.security.jwt.JwtAuthenticationFilter;
@Configuration public class SecurityConfig{private final JwtAuthenticationFilter jwt;public SecurityConfig(JwtAuthenticationFilter j){jwt=j;}@Bean SecurityFilterChain securityFilterChain(HttpSecurity http)throws Exception{return http.csrf(c->c.disable()).sessionManagement(s->s.sessionCreationPolicy(SessionCreationPolicy.STATELESS)).authorizeHttpRequests(a->a.requestMatchers("/actuator/**","/api/v1/types-espaces","/api/v1/geo/**").permitAll().requestMatchers(HttpMethod.GET,"/api/v1/espaces/{id:\\d+}").permitAll().requestMatchers(HttpMethod.POST,"/api/v1/espaces/{id:\\d+}/vue").permitAll()
  // Vérification (docs/architecture-acteurs.md §8.7) : premiers endpoints réservés à un rôle.
  // Le téléchargement d'un justificatif est ouvert à tout compte connecté : l'accès est vérifié document par document.
  .requestMatchers(HttpMethod.GET,"/api/v1/verifications/{id:\\d+}/documents/{doc:\\d+}/fichier").authenticated()
  .requestMatchers("/api/v1/verifications","/api/v1/verifications/**").hasRole("AGENT_VERIFICATION")
  .requestMatchers("/api/v1/admin/verifications","/api/v1/admin/verifications/**").hasAnyRole("ADMIN","SUPER_ADMIN")
  .anyRequest().authenticated()).addFilterBefore(jwt,UsernamePasswordAuthenticationFilter.class).build();}}
