package sn.ucad.nexora.espace.infrastructure.persistence;
import java.util.List; import java.util.Optional;
import org.springframework.stereotype.Component;
import sn.ucad.nexora.espace.domain.entity.EspaceProfessionnel; import sn.ucad.nexora.espace.domain.repository.EspaceRepository; import sn.ucad.nexora.espace.infrastructure.persistence.entity.EspaceJpaEntity;
@Component
public class EspaceRepositoryAdapter implements EspaceRepository{
 private final EspaceJpaRepository repository; public EspaceRepositoryAdapter(EspaceJpaRepository repository){this.repository=repository;}
 public EspaceProfessionnel save(EspaceProfessionnel d){return toDomain(repository.save(toEntity(d)));}
 public Optional<EspaceProfessionnel> findById(Long id){return repository.findById(id).map(this::toDomain);}
 public List<EspaceProfessionnel> findByUtilisateurId(Long id){return repository.findByUtilisateurId(id).stream().map(this::toDomain).toList();}
 public void deleteById(Long id){repository.deleteById(id);}
 private EspaceJpaEntity toEntity(EspaceProfessionnel d){EspaceJpaEntity e=new EspaceJpaEntity(); e.setId(d.getId());e.setUtilisateurId(d.getUtilisateurId());e.setTypeEspaceId(d.getTypeEspaceId());e.setNom(d.getNom());e.setSlogan(d.getSlogan());e.setDescription(d.getDescription());e.setTelephone(d.getTelephone());e.setTelephoneSecondaire(d.getTelephoneSecondaire());e.setEmail(d.getEmail());e.setSiteWeb(d.getSiteWeb());e.setLogo(d.getLogo());e.setCouverture(d.getCouverture());e.setRegistreCommerce(d.getRegistreCommerce());e.setNumeroNinea(d.getNumeroNinea());e.setNumeroRccm(d.getNumeroRccm());e.setOuvert(d.isOuvert());e.setStatut(d.getStatut());e.setCertifie(d.isCertifie());e.setVerifie(d.isVerifie());e.setNoteMoyenne(d.getNoteMoyenne());e.setNombreAvis(d.getNombreAvis());e.setNombreVues(d.getNombreVues());e.setNombreFavoris(d.getNombreFavoris());e.setDateCreation(d.getDateCreation());e.setDateCertification(d.getDateCertification());e.setDateVerification(d.getDateVerification());e.setDateModification(d.getDateModification());return e;}
 private EspaceProfessionnel toDomain(EspaceJpaEntity e){EspaceProfessionnel d=new EspaceProfessionnel();d.setId(e.getId());d.setUtilisateurId(e.getUtilisateurId());d.setTypeEspaceId(e.getTypeEspaceId());d.setNom(e.getNom());d.setSlogan(e.getSlogan());d.setDescription(e.getDescription());d.setTelephone(e.getTelephone());d.setTelephoneSecondaire(e.getTelephoneSecondaire());d.setEmail(e.getEmail());d.setSiteWeb(e.getSiteWeb());d.setLogo(e.getLogo());d.setCouverture(e.getCouverture());d.setRegistreCommerce(e.getRegistreCommerce());d.setNumeroNinea(e.getNumeroNinea());d.setNumeroRccm(e.getNumeroRccm());d.setOuvert(Boolean.TRUE.equals(e.getOuvert()));d.setStatut(e.getStatut());d.setCertifie(Boolean.TRUE.equals(e.getCertifie()));d.setVerifie(Boolean.TRUE.equals(e.getVerifie()));d.setNoteMoyenne(e.getNoteMoyenne());d.setNombreAvis(e.getNombreAvis());d.setNombreVues(e.getNombreVues());d.setNombreFavoris(e.getNombreFavoris());d.setNombreJaime(e.getNombreJaime());d.setDateCreation(e.getDateCreation());d.setDateCertification(e.getDateCertification());d.setDateVerification(e.getDateVerification());d.setDateModification(e.getDateModification());return d;}
}
