-- Extension de la taxonomie Nexora : sous-catégories pour tous les domaines
-- professionnels pertinents (référence ANSD/CCIAD/nomenclatures locales), pas
-- seulement les 12 domaines déjà détaillés. Nouvelles racines pour les domaines
-- sans équivalent existant ; les racines déjà présentes (Commerce, Informatique,
-- Automobile...) sont réutilisées telles quelles, sans renommage, pour ne casser
-- aucun type_offre/offre déjà construit dessus. Idempotent (recherche avant
-- insertion à chaque niveau).

-- Corrige les installations déjà en place : nom était globalement UNIQUE, incompatible
-- avec des sous-catégories de même nom dans des branches différentes (ex: "Services
-- administratifs" sous deux domaines distincts). Sans effet sur une base fraîche où
-- 01_categorie.sql pose déjà la contrainte par branche.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'categorie'::regclass AND contype = 'u'
               AND conkey = ARRAY[(SELECT attnum FROM pg_attribute WHERE attrelid = 'categorie'::regclass AND attname = 'nom')]) THEN
        EXECUTE (SELECT 'ALTER TABLE categorie DROP CONSTRAINT ' || quote_ident(conname)
                 FROM pg_constraint WHERE conrelid = 'categorie'::regclass AND contype = 'u'
                 AND conkey = ARRAY[(SELECT attnum FROM pg_attribute WHERE attrelid = 'categorie'::regclass AND attname = 'nom')]);
    END IF;
END $$;
CREATE UNIQUE INDEX IF NOT EXISTS uq_categorie_parent_nom ON categorie ((COALESCE(id_categorie_parent, 0)), nom);

DO $$
DECLARE
    v_paths TEXT[] := ARRAY[
        'Agriculture et élevage/Cultures céréalières/Riz',
        'Agriculture et élevage/Cultures céréalières/Mil',
        'Agriculture et élevage/Cultures céréalières/Maïs',
        'Agriculture et élevage/Cultures céréalières/Sorgho',
        'Agriculture et élevage/Cultures céréalières/Fonio',
        'Agriculture et élevage/Cultures maraîchères/Oignon',
        'Agriculture et élevage/Cultures maraîchères/Pomme de terre',
        'Agriculture et élevage/Cultures maraîchères/Tomate',
        'Agriculture et élevage/Cultures maraîchères/Carotte',
        'Agriculture et élevage/Cultures maraîchères/Chou',
        'Agriculture et élevage/Cultures maraîchères/Poivron',
        'Agriculture et élevage/Cultures fruitières/Mangue',
        'Agriculture et élevage/Cultures fruitières/Banane',
        'Agriculture et élevage/Cultures fruitières/Papaye',
        'Agriculture et élevage/Cultures fruitières/Agrumes',
        'Agriculture et élevage/Cultures fruitières/Ananas',
        'Agriculture et élevage/Cultures de rente/Arachide',
        'Agriculture et élevage/Cultures de rente/Coton',
        'Agriculture et élevage/Cultures de rente/Sésame',
        'Agriculture et élevage/Cultures de rente/Hibiscus bissap',
        'Agriculture et élevage/Élevage/Bovins',
        'Agriculture et élevage/Élevage/Ovins',
        'Agriculture et élevage/Élevage/Caprins',
        'Agriculture et élevage/Élevage/Volaille',
        'Agriculture et élevage/Élevage/Apiculture',
        'Agriculture et élevage/Services agricoles/Semences',
        'Agriculture et élevage/Services agricoles/Intrants agricoles',
        'Agriculture et élevage/Services agricoles/Travaux agricoles',
        'Agriculture et élevage/Services agricoles/Irrigation',
        'Agriculture et élevage/Services agricoles/Conseil agricole',
        'Agriculture et élevage/Matériel agricole/Tracteurs',
        'Agriculture et élevage/Matériel agricole/Motoculteurs',
        'Agriculture et élevage/Matériel agricole/Pompes',
        'Agriculture et élevage/Matériel agricole/Serres',
        'Pêche et aquaculture/Pêche/Pêche maritime',
        'Pêche et aquaculture/Pêche/Pêche artisanale',
        'Pêche et aquaculture/Pêche/Pêche industrielle',
        'Pêche et aquaculture/Aquaculture/Poissons d''élevage',
        'Pêche et aquaculture/Aquaculture/Crevettes',
        'Pêche et aquaculture/Produits de la mer/Poissons frais',
        'Pêche et aquaculture/Produits de la mer/Poissons fumés',
        'Pêche et aquaculture/Produits de la mer/Poissons séchés',
        'Pêche et aquaculture/Produits de la mer/Fruits de mer',
        'Agroalimentaire/Transformation céréalière/Farine',
        'Agroalimentaire/Transformation céréalière/Couscous',
        'Agroalimentaire/Transformation céréalière/Céréales locales',
        'Agroalimentaire/Huiles et matières grasses/Huile d''arachide',
        'Agroalimentaire/Huiles et matières grasses/Huile végétale',
        'Agroalimentaire/Produits laitiers/Lait',
        'Agroalimentaire/Produits laitiers/Yaourt',
        'Agroalimentaire/Produits laitiers/Fromage',
        'Agroalimentaire/Conserverie/Conserves',
        'Agroalimentaire/Boissons/Jus locaux',
        'Agroalimentaire/Boissons/Boissons gazeuses',
        'Agroalimentaire/Produits locaux/Miel',
        'Agroalimentaire/Produits locaux/Confitures',
        'Agroalimentaire/Produits locaux/Produits transformés locaux',
        'Agroalimentaire/Boulangerie et pâtisserie/Pain',
        'Agroalimentaire/Boulangerie et pâtisserie/Viennoiseries',
        'Agroalimentaire/Boulangerie et pâtisserie/Pâtisseries',
        'Mode et textile/Vêtements femme/Robes',
        'Mode et textile/Vêtements femme/Jupes',
        'Mode et textile/Vêtements femme/Pantalons',
        'Mode et textile/Vêtements femme/Ensembles',
        'Mode et textile/Vêtements femme/Kaftans',
        'Mode et textile/Vêtements homme/Chemises',
        'Mode et textile/Vêtements homme/Pantalons',
        'Mode et textile/Vêtements homme/Costumes',
        'Mode et textile/Vêtements homme/Boubous',
        'Mode et textile/Vêtements enfant/Fille',
        'Mode et textile/Vêtements enfant/Garçon',
        'Mode et textile/Vêtements enfant/Bébé',
        'Mode et textile/Tissus/Wax',
        'Mode et textile/Tissus/Bazin',
        'Mode et textile/Tissus/Dentelle',
        'Mode et textile/Tissus/Coton',
        'Mode et textile/Tissus/Voile',
        'Mode et textile/Chaussures/Femme',
        'Mode et textile/Chaussures/Homme',
        'Mode et textile/Chaussures/Enfant',
        'Mode et textile/Accessoires/Sacs',
        'Mode et textile/Accessoires/Ceintures',
        'Mode et textile/Accessoires/Foulards',
        'Mode et textile/Accessoires/Chapeaux',
        'Mode et textile/Services couture/Confection',
        'Mode et textile/Services couture/Retouches',
        'Mode et textile/Services couture/Broderie',
        'Mode et textile/Services couture/Teinture',
        'Beauté/Coiffure/Coiffure femme',
        'Beauté/Coiffure/Coiffure homme',
        'Beauté/Coiffure/Tresses',
        'Beauté/Coiffure/Extensions',
        'Beauté/Coiffure/Locks',
        'Beauté/Esthétique/Manucure',
        'Beauté/Esthétique/Pédicure',
        'Beauté/Esthétique/Soins du visage',
        'Beauté/Esthétique/Épilation',
        'Beauté/Maquillage/Maquillage événementiel',
        'Beauté/Maquillage/Maquillage permanent',
        'Beauté/Soins corps/Massage',
        'Beauté/Soins corps/Spa',
        'Beauté/Parfumerie/Parfums',
        'Beauté/Cosmétique/Soins visage',
        'Beauté/Cosmétique/Soins cheveux',
        'Beauté/Cosmétique/Soins corps',
        'Maison et habitat/Mobilier/Salon',
        'Maison et habitat/Mobilier/Chambre',
        'Maison et habitat/Mobilier/Bureau',
        'Maison et habitat/Décoration/Tableaux',
        'Maison et habitat/Décoration/Rideaux',
        'Maison et habitat/Décoration/Tapis',
        'Maison et habitat/Décoration/Objets décoratifs',
        'Maison et habitat/Cuisine/Ustensiles',
        'Maison et habitat/Cuisine/Vaisselle',
        'Maison et habitat/Literie/Matelas',
        'Maison et habitat/Literie/Draps',
        'Maison et habitat/Électroménager/Réfrigérateurs',
        'Maison et habitat/Électroménager/Lave-linge',
        'Maison et habitat/Électroménager/Cuisinières',
        'Maison et habitat/Jardin et extérieur/Mobilier extérieur',
        'Maison et habitat/Jardin et extérieur/Plantes',
        'Bâtiment et construction/Gros œuvre/Maçonnerie',
        'Bâtiment et construction/Gros œuvre/Béton',
        'Bâtiment et construction/Gros œuvre/Fondations',
        'Bâtiment et construction/Second œuvre/Plomberie',
        'Bâtiment et construction/Second œuvre/Électricité bâtiment',
        'Bâtiment et construction/Second œuvre/Peinture',
        'Bâtiment et construction/Second œuvre/Carrelage',
        'Bâtiment et construction/Second œuvre/Plâtrerie',
        'Bâtiment et construction/Menuiserie/Menuiserie bois',
        'Bâtiment et construction/Menuiserie/Menuiserie aluminium',
        'Bâtiment et construction/Menuiserie/Menuiserie métallique',
        'Bâtiment et construction/Climatisation et ventilation/Installation climatisation',
        'Bâtiment et construction/Climatisation et ventilation/Maintenance climatisation',
        'Bâtiment et construction/Matériaux/Ciment',
        'Bâtiment et construction/Matériaux/Fer à béton',
        'Bâtiment et construction/Matériaux/Peinture',
        'Bâtiment et construction/Architecture/Plans',
        'Bâtiment et construction/Architecture/Études techniques',
        'Automobile/Vente automobile/Voitures neuves',
        'Automobile/Vente automobile/Voitures d''occasion',
        'Automobile/Vente automobile/Motos',
        'Automobile/Pièces automobiles/Pièces moteur',
        'Automobile/Pièces automobiles/Pneus',
        'Automobile/Pièces automobiles/Batteries',
        'Automobile/Entretien/Vidange',
        'Automobile/Entretien/Freinage',
        'Automobile/Entretien/Climatisation automobile',
        'Automobile/Mécanique/Moteur',
        'Automobile/Mécanique/Embrayage',
        'Automobile/Mécanique/Transmission',
        'Automobile/Électricité automobile/Diagnostic électronique',
        'Automobile/Carrosserie/Peinture automobile',
        'Automobile/Carrosserie/Débosselage',
        'Automobile/Services automobile/Lavage',
        'Automobile/Services automobile/Dépannage',
        'Automobile/Services automobile/Remorquage',
        'Commerce/Alimentation/Épicerie',
        'Commerce/Alimentation/Fruits et légumes',
        'Commerce/Alimentation/Boucherie',
        'Commerce/Alimentation/Poissonnerie',
        'Commerce/Alimentation/Produits laitiers',
        'Commerce/Électronique/Téléphones',
        'Commerce/Électronique/Ordinateurs',
        'Commerce/Électronique/Téléviseurs',
        'Commerce/Électronique/Audio',
        'Commerce/Électronique/Accessoires mobiles',
        'Commerce/Maison/Meubles',
        'Commerce/Maison/Décoration',
        'Commerce/Bricolage/Quincaillerie',
        'Commerce/Bricolage/Plomberie',
        'Commerce/Bricolage/Électricité',
        'Commerce/Bébé/Articles bébé',
        'Commerce/Librairie et papeterie/Livres',
        'Commerce/Librairie et papeterie/Fournitures scolaires',
        'Informatique/Développement logiciel/Sites web',
        'Informatique/Développement logiciel/Applications mobiles',
        'Informatique/Développement logiciel/Logiciels métier',
        'Informatique/Réseaux/Installation réseau',
        'Informatique/Réseaux/Wi-Fi professionnel',
        'Informatique/Réseaux/Câblage réseau',
        'Informatique/Cybersécurité/Audit sécurité',
        'Informatique/Cybersécurité/Protection des données',
        'Informatique/Cloud/Cloud computing',
        'Informatique/Cloud/DevOps',
        'Informatique/Data/Business intelligence',
        'Informatique/Data/Data science',
        'Informatique/Design numérique/UI UX',
        'Informatique/Design numérique/Graphisme',
        'Informatique/Assistance informatique/Maintenance ordinateur',
        'Informatique/Assistance informatique/Réparation téléphone',
        'Électronique et électroménager/Téléphonie/Smartphones',
        'Électronique et électroménager/Téléphonie/Tablettes',
        'Électronique et électroménager/Informatique portable/PC portables',
        'Électronique et électroménager/Informatique portable/Macbooks',
        'Électronique et électroménager/Télévision/TV LED',
        'Électronique et électroménager/Audio/Enceintes',
        'Électronique et électroménager/Électroménager/Réfrigérateurs',
        'Électronique et électroménager/Électroménager/Machines à laver',
        'Électronique et électroménager/Énergie solaire/Panneaux solaires',
        'Électronique et électroménager/Énergie solaire/Batteries solaires',
        'Santé/Médecine générale/Consultation générale',
        'Santé/Spécialités/Cardiologie',
        'Santé/Spécialités/Dermatologie',
        'Santé/Spécialités/Gynécologie',
        'Santé/Spécialités/Pédiatrie',
        'Santé/Spécialités/Neurologie',
        'Santé/Spécialités/Odontologie',
        'Santé/Spécialités/Ophthalmologie',
        'Santé/Imagerie/Radiologie',
        'Santé/Imagerie/Échographie',
        'Santé/Laboratoire/Analyses médicales',
        'Santé/Pharmacie/Médicaments',
        'Santé/Pharmacie/Parapharmacie',
        'Santé/Pharmacie/Hygiène et soins',
        'Santé/Matériel médical/Mobilité',
        'Santé/Matériel médical/Diagnostic',
        'Santé/Santé mentale/Psychologie',
        'Santé/Santé mentale/Psychiatrie',
        'Éducation/Petite enfance/Préscolaire',
        'Éducation/Enseignement scolaire/Primaire',
        'Éducation/Enseignement scolaire/Collège',
        'Éducation/Enseignement scolaire/Lycée',
        'Éducation/Formation professionnelle/Informatique',
        'Éducation/Formation professionnelle/Gestion',
        'Éducation/Formation professionnelle/Industrie',
        'Éducation/Formation professionnelle/Beauté',
        'Éducation/Enseignement supérieur/Licence',
        'Éducation/Enseignement supérieur/Master',
        'Éducation/Enseignement supérieur/Doctorat',
        'Éducation/Cours particuliers/Mathématiques',
        'Éducation/Cours particuliers/Langues',
        'Éducation/Cours particuliers/Informatique',
        'Éducation/Formation en ligne/Cours vidéo',
        'Restauration/Cuisine sénégalaise/Thiéboudienne',
        'Restauration/Cuisine sénégalaise/Yassa',
        'Restauration/Cuisine sénégalaise/Mafé',
        'Restauration/Cuisine sénégalaise/Grillades',
        'Restauration/Cuisine africaine/Plats africains',
        'Restauration/Cuisine internationale/Française',
        'Restauration/Cuisine internationale/Italienne',
        'Restauration/Cuisine internationale/Asiatique',
        'Restauration/Fast-food/Burgers',
        'Restauration/Fast-food/Tacos',
        'Restauration/Pâtisserie/Gâteaux',
        'Restauration/Café et boissons/Café',
        'Hôtellerie/Hébergement/Chambres standard',
        'Hôtellerie/Hébergement/Suites',
        'Hôtellerie/Hébergement/Appartements',
        'Restauration/Événementiel et traiteur/Mariage',
        'Restauration/Événementiel et traiteur/Séminaire',
        'Transport/Transport urbain/Taxi',
        'Transport/Transport urbain/VTC',
        'Transport/Transport interurbain/Bus',
        'Transport/Transport de marchandises/Camionnage',
        'Transport/Livraison/Livraison repas',
        'Transport/Livraison/Livraison colis',
        'Transport/Coursier/Coursier express',
        'Transport/Entreposage/Stockage',
        'Transport/Déménagement/Déménagement résidentiel',
        'Transport/Déménagement/Déménagement professionnel',
        'Transport/Transit et douane/Transit',
        'Immobilier/Vente immobilière/Maisons',
        'Immobilier/Vente immobilière/Appartements',
        'Immobilier/Vente immobilière/Terrains',
        'Immobilier/Location/Location appartement',
        'Immobilier/Location/Location maison',
        'Immobilier/Location/Location bureau',
        'Immobilier/Location/Location local commercial',
        'Immobilier/Gestion immobilière/Gestion locative',
        'Immobilier/Promotion immobilière/Programmes immobiliers',
        'Immobilier/Construction immobilière/Projet résidentiel',
        'Finance et assurance/Banque/Comptes bancaires',
        'Finance et assurance/Banque/Crédit',
        'Finance et assurance/Microfinance/Microcrédit',
        'Finance et assurance/Assurance/Automobile',
        'Finance et assurance/Assurance/Santé',
        'Finance et assurance/Assurance/Habitation',
        'Finance et assurance/Transfert d''argent/Transfert national',
        'Finance et assurance/Transfert d''argent/Transfert international',
        'Finance et assurance/Fintech/Paiement mobile',
        'Juridique et administratif/Droit/Conseil juridique',
        'Juridique et administratif/Avocats/Droit des affaires',
        'Juridique et administratif/Notariat/Actes notariés',
        'Juridique et administratif/Comptabilité/Tenue comptable',
        'Juridique et administratif/Comptabilité/Audit',
        'Juridique et administratif/Fiscalité/Déclarations fiscales',
        'Juridique et administratif/Secrétariat/Saisie de données',
        'Juridique et administratif/Impression/Photocopie',
        'Juridique et administratif/Traduction/Français',
        'Juridique et administratif/Traduction/Anglais',
        'Juridique et administratif/Traduction/Wolof',
        'Conseil et services aux entreprises/Conseil/Management',
        'Conseil et services aux entreprises/Conseil/Stratégie',
        'Conseil et services aux entreprises/Ressources humaines/Recrutement',
        'Conseil et services aux entreprises/Ressources humaines/Formation entreprise',
        'Conseil et services aux entreprises/Marketing/Marketing digital',
        'Conseil et services aux entreprises/Marketing/Études de marché',
        'Conseil et services aux entreprises/Qualité/ISO',
        'Conseil et services aux entreprises/Services administratifs/Domiciliation',
        'Communication et médias/Publicité/Création publicitaire',
        'Communication et médias/Publicité/Affichage',
        'Communication et médias/Communication digitale/Réseaux sociaux',
        'Communication et médias/Communication digitale/Community management',
        'Communication et médias/Production audiovisuelle/Photographie',
        'Communication et médias/Production audiovisuelle/Vidéo',
        'Communication et médias/Production audiovisuelle/Montage',
        'Communication et médias/Imprimerie/Flyers',
        'Communication et médias/Imprimerie/Cartes de visite',
        'Communication et médias/Presse et médias/Presse en ligne',
        'Industrie et fabrication/Agro-industrie/Transformation alimentaire',
        'Industrie et fabrication/Textile/Confection industrielle',
        'Industrie et fabrication/Cuir et chaussure/Maroquinerie',
        'Industrie et fabrication/Bois/Menuiserie industrielle',
        'Industrie et fabrication/Métallurgie/Travail du métal',
        'Industrie et fabrication/Plasturgie/Produits plastiques',
        'Industrie et fabrication/Chimie/Produits chimiques',
        'Industrie et fabrication/Matériaux de construction/Produits béton',
        'Industrie et fabrication/Emballage/Cartons',
        'Industrie et fabrication/Emballage/Emballages alimentaires',
        'Artisanat et réparation/Artisanat local/Paniererie',
        'Artisanat et réparation/Artisanat local/Poterie',
        'Artisanat et réparation/Artisanat local/Bijouterie artisanale',
        'Artisanat et réparation/Artisanat local/Objets traditionnels',
        'Artisanat et réparation/Réparation/Électronique',
        'Artisanat et réparation/Réparation/Électroménager',
        'Artisanat et réparation/Réparation/Téléphones',
        'Artisanat et réparation/Réparation/Ordinateurs',
        'Culture loisirs et sport/Sport/Salle de sport',
        'Culture loisirs et sport/Sport/Fitness',
        'Culture loisirs et sport/Sport/Football',
        'Culture loisirs et sport/Sport/Arts martiaux',
        'Culture loisirs et sport/Culture/Musique',
        'Culture loisirs et sport/Culture/Danse',
        'Culture loisirs et sport/Culture/Arts visuels',
        'Culture loisirs et sport/Divertissement/Cinéma',
        'Culture loisirs et sport/Divertissement/Jeux',
        'Culture loisirs et sport/Divertissement/Parc de loisirs',
        'Événementiel/Organisation/Mariages',
        'Événementiel/Organisation/Baptêmes',
        'Événementiel/Organisation/Séminaires',
        'Événementiel/Décoration/Décoration événementielle',
        'Événementiel/Location de matériel/Tentes',
        'Événementiel/Location de matériel/Chaises et tables',
        'Événementiel/Location de matériel/Sonorisation',
        'Événementiel/Animation/DJ',
        'Événementiel/Animation/Animateur',
        'Événementiel/Photographie/Photographe événementiel',
        'Énergie et environnement/Énergie solaire/Installation solaire',
        'Énergie et environnement/Énergie solaire/Maintenance solaire',
        'Énergie et environnement/Électricité/Installation électrique',
        'Énergie et environnement/Eau/Forage',
        'Énergie et environnement/Eau/Pompage',
        'Énergie et environnement/Déchets/Collecte déchets',
        'Énergie et environnement/Déchets/Recyclage',
        'Énergie et environnement/Assainissement/Nettoyage industriel',
        'Sécurité et sûreté/Sécurité privée/Gardiennage',
        'Sécurité et sûreté/Sécurité privée/Agent de sécurité',
        'Sécurité et sûreté/Sécurité électronique/Caméras de surveillance',
        'Sécurité et sûreté/Sécurité électronique/Alarme',
        'Sécurité et sûreté/Cybersécurité/Audit',
        'Services à la personne/Ménage/Nettoyage domicile',
        'Services à la personne/Laverie et pressing/Lavage',
        'Services à la personne/Laverie et pressing/Repassage',
        'Services à la personne/Beauté/Coiffure à domicile',
        'Services à la personne/Enfants/Garde d''enfants',
        'Services à la personne/Aide à domicile/Accompagnement personnes âgées',
        'Services à la personne/Bien-être/Massage à domicile',
        'Tourisme et voyage/Voyages/Billetterie',
        'Tourisme et voyage/Voyages/Forfaits voyage',
        'Tourisme et voyage/Hébergement/Réservation hôtel',
        'Tourisme et voyage/Excursions/Visites guidées',
        'Tourisme et voyage/Transport touristique/Transfert aéroport',
        'Tourisme et voyage/Location/Location voiture',
        'Animaux/Animaux domestiques/Chiens',
        'Animaux/Animaux domestiques/Chats',
        'Animaux/Produits pour animaux/Alimentation animale',
        'Animaux/Produits pour animaux/Accessoires',
        'Animaux/Services vétérinaires/Consultation vétérinaire',
        'Animaux/Services vétérinaires/Vaccination',
        'Animaux/Toilettage/Toilettage animal',
        'Associations et action sociale/Jeunesse/Éducation',
        'Associations et action sociale/Femmes/Autonomisation',
        'Associations et action sociale/Santé/Sensibilisation',
        'Associations et action sociale/Environnement/Protection environnement',
        'Associations et action sociale/Humanitaire/Aide alimentaire',
        'Associations et action sociale/Handicap/Inclusion',
        'Associations et action sociale/Sport/Sport communautaire',
        'Administration/Administration centrale/Ministères',
        'Administration/Administration territoriale/Préfectures',
        'Administration/Collectivités territoriales/Mairies',
        'Administration/Services publics/État civil',
        'Administration/Services publics/Impôts',
        'Administration/Services publics/Sécurité sociale',
        'Administration/Diplomatie/Ambassades',
        'Administration/Diplomatie/Consulats'
    ];
    v_path TEXT; v_parts TEXT[]; v_parent BIGINT; v_id BIGINT; v_name TEXT; v_i INTEGER;
BEGIN
    FOREACH v_path IN ARRAY v_paths LOOP
        v_parts := string_to_array(v_path, '/');
        v_parent := NULL;
        FOR v_i IN 1..array_length(v_parts,1) LOOP
            v_name := trim(v_parts[v_i]);
            SELECT id_categorie INTO v_id FROM categorie
                WHERE nom = v_name AND id_categorie_parent IS NOT DISTINCT FROM v_parent;
            IF v_id IS NULL THEN
                INSERT INTO categorie(nom, id_categorie_parent, actif)
                VALUES (v_name, v_parent, TRUE)
                RETURNING id_categorie INTO v_id;
            END IF;
            v_parent := v_id;
        END LOOP;
    END LOOP;
END $$;
