package sn.ucad.nexora.espace.presentation.controller;
import java.util.List; import java.util.UUID; import jakarta.validation.Valid; import org.springframework.http.ResponseEntity; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*; import sn.ucad.nexora.espace.application.dto.request.CreateEspaceRequest; import sn.ucad.nexora.espace.application.dto.request.UpdateEspaceRequest; import sn.ucad.nexora.espace.application.dto.response.EspaceResponse; import sn.ucad.nexora.espace.application.usecase.CreateEspaceUseCase; import sn.ucad.nexora.espace.application.usecase.GetEspaceUseCase; import sn.ucad.nexora.espace.application.usecase.UpdateEspaceUseCase; import sn.ucad.nexora.espace.infrastructure.persistence.AdresseLookupRepository; import sn.ucad.nexora.espace.infrastructure.persistence.PhotoEspaceRepository; import sn.ucad.nexora.espace.infrastructure.persistence.entity.PhotoEspaceJpaEntity; import sn.ucad.nexora.espace.presentation.mapper.EspacePresentationMapper;
@RestController @RequestMapping("/api/v1/espaces") public class EspaceController{private final CreateEspaceUseCase create;private final GetEspaceUseCase get;private final UpdateEspaceUseCase update;private final AdresseLookupRepository adresses;private final PhotoEspaceRepository photos;private final EspacePresentationMapper mapper;public EspaceController(CreateEspaceUseCase c,GetEspaceUseCase g,UpdateEspaceUseCase u,AdresseLookupRepository a,PhotoEspaceRepository p,EspacePresentationMapper m){create=c;get=g;update=u;adresses=a;photos=p;mapper=m;}
 private List<String> photosDe(Long id){return photos.findByEspaceIdOrderByOrdreAffichageAsc(id).stream().map(PhotoEspaceJpaEntity::getUrl).toList();}
 @PostMapping public ResponseEntity<EspaceResponse> create(@AuthenticationPrincipal UUID accountId,@Valid @RequestBody CreateEspaceRequest r){var espace=create.create(accountId,r);var adresse=adresses.findPrincipaleByEspaceId(espace.getId()).orElse(null);return ResponseEntity.status(201).body(mapper.toResponse(espace,adresse,photosDe(espace.getId())));}
 @GetMapping("/{id}") public ResponseEntity<EspaceResponse> get(@PathVariable Long id){var espace=get.get(id);var adresse=adresses.findPrincipaleByEspaceId(id).orElse(null);return ResponseEntity.ok(mapper.toResponse(espace,adresse,photosDe(id)));}
 @GetMapping("/me") public ResponseEntity<List<EspaceResponse>> mine(@AuthenticationPrincipal UUID accountId){return ResponseEntity.ok(get.mine(accountId).stream().map(mapper::toResponse).toList());}
 @PutMapping("/{id}") public ResponseEntity<EspaceResponse> update(@AuthenticationPrincipal UUID accountId,@PathVariable Long id,@Valid @RequestBody UpdateEspaceRequest r){var espace=update.update(accountId,id,r);var adresse=adresses.findPrincipaleByEspaceId(id).orElse(null);return ResponseEntity.ok(mapper.toResponse(espace,adresse,photosDe(id)));}
}
